Disable yarn.nix update check in CI workflow
Disable the check for outdated yarn.nix files since yarn2nix does not longer work:

error: 'yarn2nix' and its tooling has been removed as it was unusable within nodePackages. Use the standard yarn v1 hooks available in nixpkgs instead.